export default {
  GET_COMMENTS: `GET_COMMENTS`,
  GET_FILMS: `GET_FILMS`,
  GET_FILMS_BY_GENRE: `GET_FILMS_BY_GENRE`,
  GET_FILMS_LIKE_THIS: `GET_FILMS_LIKE_THIS`,
  GET_PROMO_FILM: `GET_PROMO_FILM`,
  RESET_AMOUNT_RENDER_FILM_CARD: `RESET_AMOUNT_RENDER_FILM_CARD`,
  SET_AMOUNT_RENDER_FILM_CARD: `SET_AMOUNT_RENDER_FILM_CARD`,
  SET_CURRENT_FILM: `SET_CURRENT_FILM`,
  SET_CURRENT_GENRE: `SET_CURRENT_GENRE`,
};
